Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: MyFunction
      Handler: index.handler
      Role: arn:aws:iam::123456789012:role/YourExistingRoleName
      Runtime: python3.8
      Code:
        S3Bucket: mybucket
        S3Key: myfunction.zip
